default: &default
  space_id: kk2bw5ojx476
  enviroment_id: master
  access_token: 7ac531648a1b5e1dab6c18b0979f822a5aad0fe5f1109829b8a197eb2be4b84c
development:
  <<: *default
test:
  <<: *default
production:
  <<: *default